name: Build

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Select the environment
        required: true
        options:
          - production

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Log in to Google Container Registry
        run: |
          gcloud auth configure-docker europe-west1-docker.pkg.dev

      - name: Build and push Docker image to GCR
        run: |
          docker image build -t europe-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/angular-skeleton/angular-skeleton .
          docker push europe-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/angular-skeleton/angular-skeleton
